#!/bin/bash
# Script per verificare/creare utente admin in produzione Eventry
# Autore: Tech Lead Eventry
# Data: 16 Feb 2026

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║   EVENTRY - Fix Login Produzione (www.eventry.app)           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Step 1: PR su GitHub
echo "📝 STEP 1: Merge Pull Request"
echo "─────────────────────────────────────────────────────────────────"
echo "1. Vai su GitHub:"
echo "   https://github.com/andregiuseppemarketing-lgtm/eventry-ui/pull/new/fix/nextauth-production-login"
echo ""
echo "2. Clicca 'Create Pull Request'"
echo "3. Titolo: fix(auth): force NEXTAUTH_URL to www.eventry.app"
echo "4. Merge to main"
echo ""
echo "⏳ Vercel farà auto-deploy dopo il merge (2-3 minuti)"
echo ""
read -p "Premi INVIO quando hai fatto il merge..."

# Step 2: Env vars Vercel
echo ""
echo "🔧 STEP 2: Verifica Environment Variables su Vercel"
echo "─────────────────────────────────────────────────────────────────"
echo "1. Vai a: https://vercel.com/eventry-ui/settings/environment-variables"
echo ""
echo "2. Verifica che esistano per PRODUCTION:"
echo "   ✓ NEXTAUTH_URL = https://www.eventry.app"
echo "   ✓ NEXTAUTH_SECRET = <stringa 32+ caratteri>"
echo "   ✓ DATABASE_URL = postgresql://..."
echo ""
echo "3. Se NEXTAUTH_URL è diverso da www.eventry.app:"
echo "   - Modificalo"
echo "   - Fai redeploy (Dashboard → Deployments → Redeploy)"
echo ""
read -p "Premi INVIO quando hai verificato..."

# Step 3: Verifica utente admin
echo ""
echo "👤 STEP 3: Verifica/Crea Utente Admin"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "OPZIONE A - Via Vercel Dashboard (consigliato):"
echo "1. Vai a Vercel → Storage → Postgres → Data"
echo "2. Query:"
echo "   SELECT email, role FROM \"User\" WHERE email = 'admin@eventry.app';"
echo ""
echo "3. Se esiste già → Salta allo STEP 4"
echo "4. Se NON esiste:"
echo ""
echo "   INSERT INTO \"User\" ("
echo "     email, name, \"passwordHash\", role, \"emailVerified\", \"ageVerified\","
echo "     \"identityVerified\", \"onboardingCompleted\", \"createdAt\", \"updatedAt\""
echo "   ) VALUES ("
echo "     'admin@eventry.app',"
echo "     'Admin Eventry',"
echo "     '\$2a\$10\$zXvq0H8.8YjK0Z4LvZ4z3.8S9X7YZJ4K0eQZvJ8K0Z4LvZ4z3.8S9X',"  # hash di 'admin123'
echo "     'ADMIN',"
echo "     NOW(),"
echo "     true,"
echo "     true,"
echo "     true,"
echo "     NOW(),"
echo "     NOW()"
echo "   );"
echo ""
echo "   Credenziali:"
echo "   Email:    admin@eventry.app"
echo "   Password: admin123"
echo ""
echo ""
echo "OPZIONE B - Via Script (avanzato):"
echo "Richiede CONNECTION_STRING del DB produzione."
echo "1. Copia CONNECTION_STRING da Vercel → Storage → Postgres → .env.local"
echo "2. Esegui:"
echo "   DATABASE_URL='postgresql://...' npx tsx src/scripts/create-production-admin.mjs"
echo ""
read -p "Premi INVIO quando hai creato/verificato l'utente..."

# Step 4: Test login
echo ""
echo "🧪 STEP 4: Test Login"
echo "─────────────────────────────────────────────────────────────────"
echo "1. Apri browser INCOGNITO (importante!)"
echo "2. Vai a: https://www.eventry.app/auth/login"
echo "3. Credenziali:"
echo "   Email:    admin@eventry.app"
echo "   Password: admin123"
echo ""
echo "4. Dopo login, apri DevTools (F12):"
echo "   Application → Cookies → www.eventry.app"
echo "   Verifica cookie: next-auth.session-token"
echo "   Domain deve essere: .eventry.app"
echo ""
echo "5. Se login OK → Dashboard caricato ✅"
echo "   Se login KO → Controlla logs Vercel:"
echo "   vercel logs --follow | grep -i auth"
echo ""

# Step 5: Logs
echo ""
echo "📊 STEP 5: Verifica Logs (se serve debug)"
echo "─────────────────────────────────────────────────────────────────"
echo "Via CLI:"
echo "  vercel logs --follow --since 10m"
echo ""
echo "Via Dashboard:"
echo "  Vercel → Deployments → [Latest] → Logs"
echo ""
echo "Pattern da cercare:"
echo "  ✓ [NextAuth] Production URL forced to: https://www.eventry.app"
echo "  ✓ [Auth] Login successful for: admin@eventry.app"
echo "  ✗ [Auth] User not found: admin@eventry.app → Crea utente (Step 3)"
echo "  ✗ [Auth] Invalid password → Password sbagliata"
echo ""

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                      🎉 FATTO!                                ║"
echo "║                                                               ║"
echo "║  Se login funziona: problem SOLVED ✅                         ║"
echo "║  Se persiste: condividi logs Vercel per debug                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
